name: "deploy neovimcraft cron"

on:
  schedule:
  - cron: "0 */6 * * *"

env:
  GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  GITHUB_USERNAME: ${{secrets.USERNAME}}
  SRHT_ACCESS_TOKEN: ${{secrets.SRHT_ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "~1.28"
    - run: make scrape
    - run: make build

    - name: 'gcp auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS_JSON}}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Upload Site'
      run: 'gsutil -m -h "Cache-Control:private, max-age=0, no-transform" rsync -d -r ./static gs://neovimcraft.com'

    - name: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: './data/db.json'
        destination: 'neovimcraft.com/db.json'
        parent: false
        headers: |-
          cache-control: private, max-age=0, no-transform

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
